### PR TITLE
Allow c-style comments in global.json

### PR DESCRIPTION
**Pull request by dorssel**
**Description:**
Allow c-style comments in `global.json`.

**Related issue:**
Implements #254 

**Check list:**
- [ ] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by dorssel** [comment]
Initial commit was from Windows: lots of EOL trouble + differences in index.js.
Force pushed from a Linux checkout + rebuild (should solve most of the problems).

**Comment by dorssel** [comment]
`http-client.dep.yml` was split into 2 separate versions with the last merge on master: https://github.com/actions/setup-dotnet/pull/240/commits/1e92d490d2e8d6cb96b365ba3f4482d6cac7817e. Now `licensed` seems to expect a single version again.

I have no idea where `semver.dep.yml` comes from. I certainly did not add it.

**Comment by dorssel** [comment]
New info: it is the `npm` version. GitHub build environment has updated and now uses npm 8.1.2. This changes the behavior of `licensed` a lot, including adding the ones that are missing in my checks but also removing a few dozen others.

This means the current master probably will not even build itself. I don't think fixing this should be part of this pull request. Can you fix master so we can all rebase our failing pull requests on a new and working baseline?

This is also the problem with PR #250.

**Comment by vsafonkin** [comment]
Hi @dorssel, the issue with license was fixed #258 , could you update your branch from main?

**Comment by dorssel** [comment]
@vsafonkin Done

**Review by vsafonkin — APPROVED** [review]

**Comment by xt0rted** [comment]
Just ran into this issue in a new repo, any chance of getting this merged soon?

**Comment by dorssel** [comment]
@xt0rted 
This PR has been ready for merge for more than two months now. But I have no write access to this repo. And by now, there are merge conflicts which I cannot resolve, again due to missing write access. I have no clue how the workflow is for this project.

**Comment by dorssel** [comment]
.NET SDK 6.0.300 no longer allows comments in `global.json` either (although that may not be intended).
Nevertheless, this PR is stale. Not bothering to resolve merge conflicts (again...).

**Pull request closed without merging**
