### PR TITLE
Add DOTNET_ROOT

### LINKED ISSUE #11: DOTNET_ROOT for Global Tools
The DOTNET_ROOT environment variable needs to be set so that .NET Core global tools find the right locations:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreInstallerV1/dotnetcoreinstaller.ts

### PR DESCRIPTION
**Pull request by damccorm**
Fixes #11

### CODE REVIEW

**Comment by onovotny** [comment]
Does this work with SxS? It would need to point to the directory above the versioned directory, I believe. I'm not completely sure.

**Comment by damccorm** [comment]
I think you're right. Updating

**Comment by onovotny** [comment]
Notice here, https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreInstallerV1/dotnetcoreinstaller.ts#L15, it points to the a location on the agent's `dotnet` directory, not any version underneath. 

Same thing for the toolPath here: https://github.com/actions/setup-dotnet/blob/master/src/installer.ts#L62

**Comment by damccorm** [comment]
Yep. Also needs to happen even if we're pulling from the cache, so updating to do that as well

**Comment by damccorm** [comment]
Should be right now

**Comment by onovotny** [comment]
toolPath is the non-versioned path? I couldn't tell from a quick skim

**Comment by damccorm** [comment]
Ah no, didn't quite understand the ask. Sorry, bouncing between too many things right now, will drill into this now.

Right now, `toolPath` points to the directory that contains a specific version of dotnet (aka `$RUNNER_TOOL_CACHE/dncs/<version>/<arch>`)

I'll update to point to `RUNNER_TOOL_CACHE/dncs` instead, definitely is the right thing as you've suggested. Updating what we're adding to the path doesn't seem right to me though. I think we should keep that pointing to the versioned path so that `dotnet <command>` resolves to the correct version, and I don't quite understand why we would point that to the unversioned folder. Thoughts?

**Comment by onovotny** [comment]
I'm not an expert in this, but I thought there's supposed to be a muxer in the root that knows how to find the versioned dotnet underneath.

**Comment by damccorm** [comment]
My understanding is that you can do it that way, but I don't think we _need_ to. I don't see any advantages to changing to this behavior, I'm open to doing it if there are though.

My inclination is also probably to finish this PR and address that in a separate follow up issue - does that seem fair?

**Comment by sburns** [comment]
Hey y'all, I'm by no means a .Net developer, however I'm trying to get a C# lambda deployed via Actions. After setting up dotnet w/ this wonderful action and installing the lambda tools with `dotnet tool install -g Amazon.Lambda.Tools`, this log is emitted:

`Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed.`

Subsequent steps die because they can't find `dotnet-lambda`. Is this related? If not, sorry for crashing your PR.

**Comment by damccorm** [comment]
@sburns I think that's unrelated - see this issue https://github.com/dotnet/cli/issues/8368

It looks like Dotnet requires a new process to be started in order for installations to fully succeed (which is weird and seems like a bug on their end to me). We can't completely exit the process from the runner so I'm not sure there's much we can do about this.

With that said, I'm guessing that [this workaround](https://github.com/dotnet/cli/issues/8368#issuecomment-424852996) used in a different CI environment will probably work here as well?

**Comment by sburns** [comment]
@damccorm thanks for the heads up! I worked around it by writing a local action that installs the lambda tools during the image build, was the easiest way I could find to get that new process.

**Pull request merged**
