### PR TITLE
Add a way to force the architecture

### PR DESCRIPTION
**Pull request by kevingosse**
**Description:**
Add an optional `architecture` parameter to set the target architecture (x86, x64, arm64, ...).

**Related issue:**
https://github.com/actions/setup-dotnet/issues/72

**Check list:**
- [x] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by kevingosse** [comment]
Any idea why the checks are failing on ubuntu/mac-OS? It looks like it produce a different dist.js, but I did run `npm build` and include the result to the PR.

**Comment by vsafonkin** [comment]
> Any idea why the checks are failing on ubuntu/mac-OS? It looks like it produce a different dist.js, but I did run `npm build` and include the result to the PR.

@kevingosse could you try to remove `index.js` from dist directory and rebuild it again via `npm run build`?

**Comment by kevingosse** [comment]
@vsafonkin I tried but it produces an identical file:
```
C:\git\setup-dotnet>del dist\index.js

C:\git\setup-dotnet>npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> setup-dotnet@1.0.0 build
> tsc && ncc build

ncc: Version 0.33.4
ncc: Compiling file index.js into CJS
1109kB  dist\index.js
1109kB  [1020ms] - ncc 0.33.4

C:\git\setup-dotnet>git status
On branch kevin/architecture
Your branch is up to date with 'origin/kevin/architecture'.

nothing to commit, working tree clean
```

**Comment by IvanZosimov** [comment]
Hi, @kevingosse 👋 Sorry for the delay, could I ask you to update your PR? There is a merge conflict because of the new released major version of the action.

**Comment by kevingosse** [comment]
Creating a new branch and redoing the change because there are just too many conflicts: https://github.com/actions/setup-dotnet/pull/298

**Comment by tilemanrenovations** [comment]
I am applying to the string G-#47918

**Pull request closed without merging**
