### PR TITLE
Update README.md to use latest action version

### PR DESCRIPTION
**Pull request by mikes-gh**
update README with latest version

**Description:**
I wasn't immediately aware that v4 was the current version.
It's in releases but I think the README should reflect the latest version particularly since v3 gives depreciation warnings

**Related issue:**
Add link to the related issue.

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Review by aparnajyothi-y — APPROVED** [review]

**Comment by mikes-gh** [comment]
Actually, I just noticed the find and replace changed the NuGet URL.  Let me change that.

**Review by Saibamen — APPROVED** [review]
LGTM

**Comment by bernhardkaindl** [comment]
@nikolai-laevskii @aparnajyothi-y I hope you are not ill, can you click "merge"?

**Review by bernhardkaindl — APPROVED** [review]

**Review by bernhardkaindl — APPROVED** [review]
@nikolai-laevskii @aparnajyothi-y I hope you are not ill, can you click "merge"?

**Review by aparnajyothi-y — APPROVED** [review]

**Review by shaanmugapriya — APPROVED** [review]

**Review by HarithaVattikuti — APPROVED** [review]

**Comment by Maclain33** [comment]
**Maclain33**

>  let this repo to get approve  and Merged it.

**Pull request merged**
