### PR TITLE
V2 setup-dotnet ADR

### PR DESCRIPTION
**Pull request by vsafonkin**
This PR outlines the basic proposals for the v2 version of setup-dotnet.

Internal issue: [1807](https://github.com/actions/virtual-environments-internal/issues/1807)

[comment](https://github.com/actions/setup-dotnet/pull/171#discussion_r627211129):
### To summarize the current behavior for .NET team review
We have a bunch of .NET Core versions pre-installed on images. And the problem is that action works very inconsistent on different platforms.

- Ubuntu:
Pre-installed location (where .NET is pre-installed): “/usr/share/dotnet”
Action installs to: “/home/runner/.dotnet”
- Windows:
Pre-installed location:  “C:\Program Files\dotnet”
Action installs to “C:\Users\runneradmin\AppData\Local\Microsoft\dotnet”
- MacOS:
Pre-installed location: “/Users/runner/.dotnet”
Action installs to “/Users/runner/.dotnet”
 
### How it works currently on macOS
Pre-installed location and action location are the same. It means that if we have versions `2.1.x`, `3.1.x` and `5.0.x` pre-installed on image and user will install 3.1 via action, installation will be skipped because version already exists. if customer runs `dotnet --version` it will report version 5.x if customer doesn't have global.json (because both 2.1, 3.1, 5.0 will be located in the same folder and `dotnet` will choose the latest one based on https://docs.microsoft.com/en-us/dotnet/core/versions/selection)

### How it works currently on Windows / Ubuntu
Pre-installed location and action location are different. It means if we have versions `2.1.x`, `3.1.x` and `5.0.x` pre-installed on image and user will install 3.1 via action, version 3.1 will be installed to the separate location and `dotnet --version` will report version 3.1 because it is the single version installed in that location.

### Problems
Behavior is inconsistent between platforms and it confuses users
macOS users complain that dotnet still uses 5.x despite the fact that they invoked action with 3.1
Windows / Ubuntu users complain that pre-installed .NET are not consumed and it is always installed that takes build time
In our understand, the correct behavior is on macOS right now.
The new versions should be installed in the same location like pre-installed. It is expected behavior that `dotnet --version` will point the latest one and we should just point customers to documentation.

### CODE REVIEW

**Review by AlenaSviridenko — APPROVED** [review]

**Comment by Rhinowiwina** [comment]
run-it

**Comment by Rhinowiwina** [comment]
From 09c173630b10065b2bcc1eed8dc8e20dc26de8fb Mon Sep 17 00:00:00 2001
From: Vladimir Safonkin <vsafonkin@github.com>
Date: Mon, 21 Jun 2021 13:05:18 +0300
Subject: [PATCH 1/4] ADR

---
 docs/adrs/v2-setup-dotnet.md | 31 +++++++++++++++++++++++++++++++
 1 file changed, 31 insertions(+)
 create mode 100644 docs/adrs/v2-setup-dotnet.md

diff --git a/docs/adrs/v2-setup-dotnet.md b/docs/adrs/v2-setup-dotnet.md
new file mode 100644
index 00000000..b3cac3d7
--- /dev/null
+++ b/docs/adrs/v2-setup-dotnet.md
@@ -0,0 +1,31 @@
+# V2 setup-dotnet
+
+Date: 2021-02-15
+Status: Proposed
+
+# Context
+- GitHub-hosted Ubuntu and Windows runners have .NET versions pre-installed in system directories (Ubuntu:`/usr/share/dotnet`, Windows:`C:\Program Files\dotnet`), but the `v1` version of action installs .NET to user's directory (Ubuntu:`/home/runner/.dotnet`, Windows: `C:\Users\runneradmin\AppData\Local\Microsoft\dotnet`) for that runners. It means that action always download and install .NET version even if it is pre-installed and after using the action all pre-installed .NET versions are unavailable.
+The behavior is different for macOS runners because pre-installation directory matches the one that is used by action. It means action can use pre-installed versions if it exists, which speeds up customer's workflow.
+
+- The different behavior of setup task on Ubuntu, Windows and MacOS runners is being unclear and confusing for customers.
+
+- .NET supports installing and using multiple versions of .NET SDK and .NET runtime sidy-by-side and .NET CLI will use the latest of installed .NET SDK and .NET runtime version, this behavior is defined by .NET design (https://docs.microsoft.com/en-us/dotnet/core/versions/selection). The common practice is specifying required versions in project file. From other side, the presence of pre-installed .NET versions that are higher than version that the customers specify in the setup task can be breaking for some customers, who expect only one installed .NET version on runner after using setup task, so we should release new task version for consistent behavior on all runners and avoid breaking changes.
+
+- The action contains logic to handle inputs with wildcards, for example `5.0.x`, `5.0.*`, `5.x` or `5.*`. This logic uses metadata from `https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json` to retrieve list of available releases and get the latest release version for the specified major and/or minor version from input. After that, installer script (`dotnet-install.ps1` for Windows or `dotnet-install.sh` for Linux and MacOS) installs required SDK using exact version as parameter. We can get rid of this unnecessary logic in action since installer scripts have similar logic to find the latest release if the script is invoked with `channel` option. Example: the execution `dotnet-install.ps1 -Channel 5.0` installs the latest patch version for 5.0 sdk. In this way we can handle inputs with wildcard as patch version (`5.0.x` or `5.0.*`) by passing major and minor version to installer script directly as `channel` parameter. This parameter supports two-part version in X.Y format as input values ([see installer scripts documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)). The inputs with wildcard as minor version (`5.x`) should be unsupported in V2 version of the action.
+
+# Proposal
+- Change .NET installation path for Windows and Ubuntu images to match the location of pre-installed versions by using `-InstallDir` (Windows) and `--install-dir` (Ubuntu) property for installer scripts:
+https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
+- Get rid of redundant logic for retrieving releases metadata to find exact version and use possibilities of installer scripts for these operations to handle inputs with wildcards.
+- Release new task version to avoid breaking changes for customers.
+
+# v2-preview
+There will be a v2-preview branch that will be created for development and testing. Any changes will first be merged into v2-preview branch. After a period of testing & verification, the v2-preview branch will be merged into the main branch and a v2 tag will be created. Any GitHub public documentation and starter workflows that mention setup-dotnet will then be updated to use v2 instead of v1:
+- [README.md](https://github.com/actions/setup-dotnet/blob/main/README.md)
+- [action.yml](https://github.com/actions/setup-dotnet/blob/main/action.yml)
+- [GitHub docs](https://docs.github.com/en/actions/guides/building-and-testing-net#using-a-specific-net-version)
+- Starter-workflow yamls: [#1](https://github.com/actions/starter-workflows/blob/main/ci/dotnet.yml#L17), [#2](https://github.com/actions/starter-workflows/blob/main/ci/dotnet-desktop.yml#L72)
+
+# Consequences
+- Customers will be able to use pre-installed .NET versions with setup-dotnet action on Windows and Ubuntu.
+- Maintanance of the action will be easier due the simplier logic of handling inputs with wildcards.
\ No newline at end of file

From 4e1a1deef2537702715844e7650db0be9f47c90a Mon Sep 17 00:00:00 2001
From: Vladimir Safonkin <vsafonkin@github.com>
Date: Mon, 21 Jun 2021 13:41:14 +0300
Subject: [PATCH 2/4] Version input for installers scripts

---
 docs/adrs/v2-setup-dotnet.md | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/docs/adrs/v2-setup-dotnet.md b/docs/adrs/v2-setup-dotnet.md
index b3cac3d7..d7e77af2 100644
--- a/docs/adrs/v2-setup-dotnet.md
+++ b/docs/adrs/v2-setup-dotnet.md
@@ -11,7 +11,9 @@ The behavior is different for macOS runners because pre-installation directory m
 
 - .NET supports installing and using multiple versions of .NET SDK and .NET runtime sidy-by-side and .NET CLI will use the latest of installed .NET SDK and .NET runtime version, this behavior is defined by .NET design (https://docs.microsoft.com/en-us/dotnet/core/versions/selection). The common practice is specifying required versions in project file. From other side, the presence of pre-installed .NET versions that are higher than version that the customers specify in the setup task can be breaking for some customers, who expect only one installed .NET version on runner after using setup task, so we should release new task version for consistent behavior on all runners and avoid breaking changes.
 
-- The action contains logic to handle inputs with wildcards, for example `5.0.x`, `5.0.*`, `5.x` or `5.*`. This logic uses metadata from `https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json` to retrieve list of available releases and get the latest release version for the specified major and/or minor version from input. After that, installer script (`dotnet-install.ps1` for Windows or `dotnet-install.sh` for Linux and MacOS) installs required SDK using exact version as parameter. We can get rid of this unnecessary logic in action since installer scripts have similar logic to find the latest release if the script is invoked with `channel` option. Example: the execution `dotnet-install.ps1 -Channel 5.0` installs the latest patch version for 5.0 sdk. In this way we can handle inputs with wildcard as patch version (`5.0.x` or `5.0.*`) by passing major and minor version to installer script directly as `channel` parameter. This parameter supports two-part version in X.Y format as input values ([see installer scripts documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)). The inputs with wildcard as minor version (`5.x`) should be unsupported in V2 version of the action.
+- The action contains logic to handle inputs with wildcards, for example `5.0.x`, `5.0.*`, `5.x` or `5.*`. This logic uses metadata from `https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json` to retrieve list of available releases and get the latest release version for the specified major and/or minor version from input. After that, installer script (`dotnet-install.ps1` for Windows or `dotnet-install.sh` for Linux and MacOS) installs required SDK using exact version as parameter. We can get rid of this unnecessary logic in action since installer scripts have similar logic to find the latest release if the script is invoked with `channel` option. Example: the execution `dotnet-install.ps1 -Channel 5.0` installs the latest patch version for 5.0 sdk. In this way we can handle inputs with wildcard as patch version (`5.0.x` or `5.0.*`) by passing major and minor version to installer script directly as `channel` parameter. This parameter supports two-part version in X.Y format as input values ([see installer scripts documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)). In further the version input format of action will follow the format which is supported by installers scripts. 
+
+Breaking changes: the inputs with wildcard as minor version (`5.x`) can't be processed as correct format for installer scripts, so these inputs should be unsupported in V2 version of the action.
 
 # Proposal
 - Change .NET installation path for Windows and Ubuntu images to match the location of pre-installed versions by using `-InstallDir` (Windows) and `--install-dir` (Ubuntu) property for installer scripts:

From b508d01493f548835212a0d5c83c33fa6410ddce Mon Sep 17 00:00:00 2001
From: Maxim Lobanov <maxim-lobanov@github.com>
Date: Wed, 30 Jun 2021 08:52:06 +0300
Subject: [PATCH 3/4] Update v2-setup-dotnet.md

---
 docs/adrs/v2-setup-dotnet.md | 35 +++++++++++++++++++++++++----------
 1 file changed, 25 insertions(+), 10 deletions(-)

diff --git a/docs/adrs/v2-setup-dotnet.md b/docs/adrs/v2-setup-dotnet.md
index d7e77af2..f24deef8 100644
--- a/docs/adrs/v2-setup-dotnet.md
+++ b/docs/adrs/v2-setup-dotnet.md
@@ -1,25 +1,40 @@
 # V2 setup-dotnet
 
-Date: 2021-02-15
+Date: 2021-06-30  
 Status: Proposed
 
 # Context
-- GitHub-hosted Ubuntu and Windows runners have .NET versions pre-installed in system directories (Ubuntu:`/usr/share/dotnet`, Windows:`C:\Program Files\dotnet`), but the `v1` version of action installs .NET to user's directory (Ubuntu:`/home/runner/.dotnet`, Windows: `C:\Users\runneradmin\AppData\Local\Microsoft\dotnet`) for that runners. It means that action always download and install .NET version even if it is pre-installed and after using the action all pre-installed .NET versions are unavailable.
+- GitHub-hosted Ubuntu and Windows runners have .NET versions pre-installed in system directories
+  - Ubuntu:`/usr/share/dotnet`
+  - Windows:`C:\Program Files\dotnet`
+- V1 version of Action installs .NET to user's directory
+  - Ubuntu:`/home/runner/.dotnet`
+  - Windows: `C:\Users\runneradmin\AppData\Local\Microsoft\dotnet`
+- It means that action always download and install .NET version even if it is pre-installed. Also after using the action all pre-installed .NET versions are unavailable because `DOTNET_ROOT` is overriden to user directory.
 The behavior is different for macOS runners because pre-installation directory matches the one that is used by action. It means action can use pre-installed versions if it exists, which speeds up customer's workflow.
 
 - The different behavior of setup task on Ubuntu, Windows and MacOS runners is being unclear and confusing for customers.
 
-- .NET supports installing and using multiple versions of .NET SDK and .NET runtime sidy-by-side and .NET CLI will use the latest of installed .NET SDK and .NET runtime version, this behavior is defined by .NET design (https://docs.microsoft.com/en-us/dotnet/core/versions/selection). The common practice is specifying required versions in project file. From other side, the presence of pre-installed .NET versions that are higher than version that the customers specify in the setup task can be breaking for some customers, who expect only one installed .NET version on runner after using setup task, so we should release new task version for consistent behavior on all runners and avoid breaking changes.
+- .NET supports installing and using multiple versions of .NET SDK and .NET runtime sidy-by-side and .NET CLI will use **the latest** of installed .NET SDK and .NET runtime version, this behavior is defined by .NET design (https://docs.microsoft.com/en-us/dotnet/core/versions/selection). The recommended practice is [specifying required versions in project file](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version).
 
-- The action contains logic to handle inputs with wildcards, for example `5.0.x`, `5.0.*`, `5.x` or `5.*`. This logic uses metadata from `https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json` to retrieve list of available releases and get the latest release version for the specified major and/or minor version from input. After that, installer script (`dotnet-install.ps1` for Windows or `dotnet-install.sh` for Linux and MacOS) installs required SDK using exact version as parameter. We can get rid of this unnecessary logic in action since installer scripts have similar logic to find the latest release if the script is invoked with `channel` option. Example: the execution `dotnet-install.ps1 -Channel 5.0` installs the latest patch version for 5.0 sdk. In this way we can handle inputs with wildcard as patch version (`5.0.x` or `5.0.*`) by passing major and minor version to installer script directly as `channel` parameter. This parameter supports two-part version in X.Y format as input values ([see installer scripts documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)). In further the version input format of action will follow the format which is supported by installers scripts. 
-
-Breaking changes: the inputs with wildcard as minor version (`5.x`) can't be processed as correct format for installer scripts, so these inputs should be unsupported in V2 version of the action.
+- The action contains logic to handle inputs with wildcards, for example `5.0.x`, `5.0.*`, `5.x` or `5.*`. This logic uses metadata from `https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json` to retrieve the list of available releases and get the latest release version for the specified major and/or minor version from input. After that, installer script (`dotnet-install.ps1` for Windows or `dotnet-install.sh` for Linux and MacOS) installs required SDK using exact version as a parameter.
 
 # Proposal
 - Change .NET installation path for Windows and Ubuntu images to match the location of pre-installed versions by using `-InstallDir` (Windows) and `--install-dir` (Ubuntu) property for installer scripts:
 https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
-- Get rid of redundant logic for retrieving releases metadata to find exact version and use possibilities of installer scripts for these operations to handle inputs with wildcards.
-- Release new task version to avoid breaking changes for customers.
+- Get rid of redundant logic to resolve wildcard version on Action side and start relying on [official installer scripts provided by .NET Core team](https://github.com/dotnet/install-scripts).  
+The execution `dotnet-install.ps1 -Channel 5.0` installs the latest patch version for 5.0 sdk. In this way we can handle inputs with wildcard as patch version (`5.0.x` or `5.0.*`) by passing major and minor version to installer script directly as `channel` parameter. This parameter supports two-part version in X.Y format as input values ([see installer scripts documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)). In further the version input format of action will follow the format which is supported by installers scripts. 
+
+# Breaking changes
+- The presence of pre-installed .NET versions that are higher than version that the users specify in the setup task can be breaking for some customers, who expect only one installed .NET version on runner after using setup task. If user doesn't have .NET version specified in project file, `dotnet` will use the latest installed version instead of provided in setup task.  
+> **Note:** It is the biggest deal in this ADR.
+Previously, when user specifies .NET version, this exact version was used by `dotnet` command by default (because it was installed in the separate folder and there are no any other .NET versions in that folder)  
+In proposal, the specified version will be installed on machine but the latest version will be used by `dotnet` command by default (because specified version will be installed alongside with pre-installed .NET versions).  
+Based on [official .NET documentation](https://docs.microsoft.com/en-us/dotnet/core/versions/selection), it is expected behavior and how it works on user's local machine with multiple installed .NET versions but some customers could be broken because they already rely on current behavior.
+
+- All possible inputs will continue to work as previously except `5.x`. It is totally okay to drop it because we shouldn't allow user to rely on such input. New minor release of .NET will break their builds
+
+To avoid breaking customers, we will need to release new major task version (V2).
 
 # v2-preview
 There will be a v2-preview branch that will be created for development and testing. Any changes will first be merged into v2-preview branch. After a period of testing & verification, the v2-preview branch will be merged into the main branch and a v2 tag will be created. Any GitHub public documentation and starter workflows that mention setup-dotnet will then be updated to use v2 instead of v1:
@@ -29,5 +44,5 @@ There will be a v2-preview branch that will be created for development and testi
 - Starter-workflow yamls: [#1](https://github.com/actions/starter-workflows/blob/main/ci/dotnet.yml#L17), [#2](https://github.com/actions/starter-workflows/blob/main/ci/dotnet-desktop.yml#L72)
 
 # Consequences
-- Customers will be able to use pre-installed .NET versions with setup-dotnet action on Windows and Ubuntu.
-- Maintanance of the action will be easier due the simplier logic of handling inputs with wildcards.
\ No newline at end of file
+- Customers will be able to use pre-installed .NET versions with setup-dotnet action on Windows and Ubuntu
+- Maintenance of the action will be easier due the simplier logic of handling inputs with wildcards

From 41e01013a8ce5aa752877b437e1b9c0b2feea2e1 Mon Sep 17 00:00:00 2001
From: Maxim Lobanov <maxim-lobanov@github.com>
Date: Wed, 30 Jun 2021 12:27:59 +0300
Subject: [PATCH 4/4] Update v2-setup-dotnet.md

---
 docs/adrs/v2-setup-dotnet.md | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/docs/adrs/v2-setup-dotnet.md b/docs/adrs/v2-setup-dotnet.md
index f24deef8..4e585f7c 100644
--- a/docs/adrs/v2-setup-dotnet.md
+++ b/docs/adrs/v2-setup-dotnet.md
@@ -13,9 +13,9 @@ Status: Proposed
 - It means that action always download and install .NET version even if it is pre-installed. Also after using the action all pre-installed .NET versions are unavailable because `DOTNET_ROOT` is overriden to user directory.
 The behavior is different for macOS runners because pre-installation directory matches the one that is used by action. It means action can use pre-installed versions if it exists, which speeds up customer's workflow.
 
-- The different behavior of setup task on Ubuntu, Windows and MacOS runners is being unclear and confusing for customers.
+- The different behavior of setup task on Ubuntu, Windows and MacOS runners is unclear and confusing for customers.
 
-- .NET supports installing and using multiple versions of .NET SDK and .NET runtime sidy-by-side and .NET CLI will use **the latest** of installed .NET SDK and .NET runtime version, this behavior is defined by .NET design (https://docs.microsoft.com/en-us/dotnet/core/versions/selection). The recommended practice is [specifying required versions in project file](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version).
+- .NET supports installing and using multiple versions of .NET SDK and .NET runtime sidy-by-side. .NET CLI will use the latest of installed .NET SDK and .NET runtime version if there is no global.json file containing a different version. This behavior is defined by .NET design (https://docs.microsoft.com/en-us/dotnet/core/versions/selection).
 
 - The action contains logic to handle inputs with wildcards, for example `5.0.x`, `5.0.*`, `5.x` or `5.*`. This logic uses metadata from `https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json` to retrieve the list of available releases and get the latest release version for the specified major and/or minor version from input. After that, installer script (`dotnet-install.ps1` for Windows or `dotnet-install.sh` for Linux and MacOS) installs required SDK using exact version as a parameter.

**Comment by Rhinowiwina** [comment]
drun

**Comment by Rhinowiwina** [comment]
Hod

**Comment by Rhinowiwina** [comment]
dffa

**Comment by monstro805** [comment]
good work everyone thank you

**Comment by Liton23** [comment]
Excellent this project

**Comment by Liton23** [comment]
Excellent

**Comment by mattjohnsonpint** [comment]
So... v2 released Feb 25th.  Was none of this addressed?  Is this for v3 now?

**Comment by vsafonkin** [comment]
@mattjohnsonpint, thanks! Re-create this PR because I have lost the branch `v-vlsafo/adr-v2-doc` in my fork.
New PR: https://github.com/actions/setup-dotnet/pull/291

**Pull request closed without merging**
