### PR TITLE
Fix for 5.x notation

### PR DESCRIPTION
**Pull request by dmitry-shibanov**
**Description:**
In scope of this pull request we fix issue with build failure for 5.x notation.
**Related issue:** https://github.com/actions/setup-dotnet/issues/173

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Review by vsafonkin — APPROVED** [review]

**Review by maxim-lobanov — APPROVED** [review]

**Review by MaksimZhukov — APPROVED** [review]

**Comment by GGG-KILLER** [comment]
I remember the reason `major.x` wasn't implemented was because of the issue with .NET Core 2.x since 2.2 support has been dropped and 2.1 is the LTS version (so installing 2.2 in this case would be undesirable).

Is this still the case?

**Comment by dmitry-shibanov** [comment]
Hello @GGG-KILLER. I think we can proceed with this pull request because we add logic for installing latest minor version. In our understanding, If customer wants to use latest minor version, they should be aware of unexpected breaking changes in new versions.

**Comment by GGG-KILLER** [comment]
> Hello @GGG-KILLER. I think we can proceed with this pull request because we add logic for installing latest minor version. In our understanding, If customer wants to use latest minor version, they should be aware of unexpected breaking changes in new versions.

Fair enough, however, I think maybe we should consider adding a helpful error message informing the user that they version they're installing is unsupported and that it might not work in the GitHub-hosted runners (for example, 2.2 doesn't).

**Comment by dmitry-shibanov** [comment]
Hello @GGG-KILLER . I'm not sure that we should create warning in the action about deprecated version of NET Core. In my opinion possibly it will require from us manual support of adding next deprecated versions to warning. Would it be better to update documentation with the [link](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) for supported and expired support versions ?

**Comment by GGG-KILLER** [comment]
> Hello @GGG-KILLER . I'm not sure that we should create warning in the action about deprecated version of NET Core. In my opinion possibly it will require from us manual support of adding next deprecated versions to warning. Would it be better to update documentation with the [link](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) for supported and expired support versions ?

@dmitry-shibanov The API we use to retrieve .NET versions actually includes the EOL (end of support) date for that version, so it *should* be as simple as a current date check. But I don't think this should stop this PR from being merged, this should be another issue that should be treated separately.

**Pull request merged**
