### PR TITLE
add .dotnet/tools to path

### LINKED ISSUE #69: .dotnet/tools is not on path
Trying to install codecov.tool and use it appears that `.dotnet/tool` is not on path.

https://github.com/casz/GitLabApiClient/blob/b295527722130004e1c2125d2e8055f68721d41c/.github/workflows/ci.yml
https://github.com/nmklotas/GitLabApiClient/blob/b295527722130004e1c2125d2e8055f68721d41c/test.ps1

https://github.com/nmklotas/GitLabApiClient/pull/100/checks?check_run_id=359089103#step:7:486

### PR DESCRIPTION
**Pull request by casz**
fixes #69

### CODE REVIEW

**Comment by casz** [comment]
hmm adding a test case?

**Comment by casz** [comment]
definitely fixes my issue:

https://github.com/casz/setup-dotnet-global-tool-repro/commit/f0b18d98a454cd26f7ddd655d652c4abe3743a07/checks?check_suite_id=369607404
https://github.com/casz/setup-dotnet-global-tool-repro/blob/testingFix/.github/workflows/ci.yml

**Comment by bryanmacfarlane** [comment]
If it's the globally installed tools in the virtual machine, isn't this really an issue in https://github.com/actions/virtual-environments ?  In other words, if I didn't use the setup-dotnet action and dotnettools are installed on the image, shouldn't it be in the path?

**Comment by casz** [comment]
These global tools are usually installed with dotnet cli so kind of related. I can definitely add it to the virtual environments but that fix could take weeks before it is applied 🤔

**Comment by bryanmacfarlane** [comment]
Yeah, I think it's a question of who laid those bits down (the vm gen scripts or this action).  If this action mutates that global installed path then I agree.  If it's part of image gen, then I would do there.

**Comment by casz** [comment]
I guess that is the question, where should the work be done? 🤔

**Comment by casz** [comment]
So you suggest I do the work here:
https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-DotnetSDK.ps1
https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/dotnetcore.sh

for macos I am not sure, still learning the virtual-environments source code.

**Comment by bryanmacfarlane** [comment]
Log an issue for mac-os (I don't think they open sourced those yet)

**Comment by casz** [comment]
After more testing it seems like a bug in the Linux and MacOS virtual environments as this actually works on Windows: https://github.com/casz/setup-dotnet-global-tool-repro/runs/366837035

**Comment by ZEisinger** [comment]
Issue has been opened against virtual-environments for this issue. This action currently does not use the global install location and the machine should set the appropriate path if it has used the global install location.

**Pull request closed without merging**
