### PR TITLE
Include useful environment variables in the README

### PR DESCRIPTION
**Pull request by ZEisinger**
Fixes: #91, #10, #22 
These do not change any dotnet defaults, but adds documentation to make defaults and uses clear to users.

### CODE REVIEW

**Comment by thashepherd** [comment]
Thanks for documenting this! I just ran https://github.com/Aurora-Modders/AuroraLoader/runs/722001214?check_suite_focus=true using 

```
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
      env:
        DOTNET_NOLOGO: true
    - run: dotnet test
```
and got the following output in the test step:
```
> Run dotnet test

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.300

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
```
which indicates that something may be up

**Comment by ZEisinger** [comment]
Thanks for trying this out, it looks like I misunderstood how these flags work. The environment variables need to be scoped for the whole build and not just the install action.

**Comment by ZEisinger** [comment]
Thanks for trying this out, it looks like I misunderstood how these flags work. The environment variables need to be scoped for the whole workflow and not just the install action.

**Comment by thashepherd** [comment]
Updated docs worked like a charm (https://github.com/Aurora-Modders/AuroraLoader/pull/63/checks?check_run_id=727946131) - thanks!

**Pull request merged**
